file:
  df_image: 'n5907_df_r.fits'
  hi_res_image_blue: 'n5907_cfht_g.fits'
  hi_res_image_red: 'n5907_cfht_r.fits'
  certain_gal_cat: 'gal_cat.txt'
  hi_res_zp: 30.0

DF:
  band: 'r'
  pixel_scale: 2.5
  sub_bkgval: True # highly recommend True
  magnify_factor: 3.0
  resize_method: 'iraf'
  zeropoint: 27.0  # don't be very accurate
  color_term: 0    # -0.15

sex:
  sigma: 2.5
  minarea: 3
  b: 64
  f: 3
  deblend_cont: 0.0005
  deblend_nthresh: 32
  sky_subtract: False
  flux_aper: [3, 6]
  show_fig: False

star:
  method: 'gaia'
  bright_lim: 17.5

fluxmodel:
  gaussian_radius: 1.5     # mask = convolve(mask, Gaussian2DKernel(1.5))
  gaussian_threshold: 0.05 # mask = mask > 0.05
  unmask_lowsb: True
  sb_lim: 24.0
  unmask_ratio: 0.1 # This value is suspicious!!!

kernel:
  kernel_size: 8 # In original coordinate, before magnification
  kernel_edge: 1
  nkernel: 25
  cval: 0.0
  frac_maxflux: 0.05
  circularize: False
  show_fig: True

starhalo:
  method: 'apass'
  bright_lim: 15 # only stack stars brighter than bright_lim
  fwhm_lim: 20 # only stack stars whose FWHM < fwhm_lim
  n_stack: 30
  halosize: 45 # radial size, in pixel
  padsize: 50
  edgesize: 3
  norm: 'flux_ann' # or 'flux_ann'
  sigma: 4.5
  minarea: 5
  deblend_cont: 0.005
  deblend_nthresh: 32
  sky_subtract: False
  flux_aper: [3, 6]
  show_fig: False
  cval: np.nan

clean:
  clean_img: True
  clean_file: True
  replace_with_noise: True
  gaussian_radius: 2.5
  star_method: 'usno'
  bright_lim: 20
